import { ReadingLog } from '../types';

export const INITIAL_SAMPLE_LOGS: ReadingLog[] = [
  {
    id: 'sample_log_1',
    grade: 5,
    classNum: 2,
    studentName: '김민준',
    bookTitle: '마당을 나온 암탉',
    author: '황선미',
    publisher: '사계절',
    genre: '문학',
    readDate: '2026-07-20',
    rating: 5,
    summary: '양계장을 탈출한 암탉 잎싹이가 아기 오리 초록이를 정성껏 키우며 모성애와 자유의 소중함을 보여주는 이야기입니다. 잎싹이의 용기 있는 삶과 희생이 깊은 감동을 줍니다.',
    thoughts: '잎싹이가 초록이를 위험에서 구하기 위해 족제비와 싸우는 장면에서 눈물이 났습니다. 나를 사랑해주시는 부모님의 마음을 생각하게 되었고, 자유를 향한 잎싹이의 꿈이 참 아름답게 느껴졌습니다.',
    isFeatured: true,
    teacherComment: '잎싹이의 모성애와 부모님의 사랑을 연결 지어 솔직하고 감동 깊게 서술했습니다. 아주 훌륭한 독서록입니다!',
    createdAt: '2026-07-20T10:00:00.000Z'
  },
  {
    id: 'sample_log_2',
    grade: 5,
    classNum: 2,
    studentName: '이서연',
    bookTitle: '어린 왕자',
    author: '앙투안 드 생텍쥐페리',
    publisher: '열린책들',
    genre: '문학',
    readDate: '2026-07-22',
    rating: 5,
    summary: '사막에 불시착한 조종사가 B612 행성에서 온 어린 왕자를 만나 여러 행성을 여행한 이야기를 듣게 됩니다. 길들임과 책임감, 눈에 보이지 않는 중요한 것들에 대한 진리를 배웁니다.',
    thoughts: '"가장 중요한 것은 눈에 보이지 않아"라는 여우의 말이 마음속 깊이 남았습니다. 내 곁에 있는 친구들과 가족들을 더 아끼고 진심으로 다가가야겠다고 다짐했습니다.',
    isFeatured: true,
    teacherComment: '어린 왕자의 명언을 자기 생활과 연관 지어 깊이 있게 표현했네요. 참 예쁜 마음입니다.',
    createdAt: '2026-07-22T14:30:00.000Z'
  },
  {
    id: 'sample_log_3',
    grade: 5,
    classNum: 2,
    studentName: '김민준',
    bookTitle: '자전거 도둑',
    author: '박완서',
    publisher: '다림',
    genre: '문학',
    readDate: '2026-07-24',
    rating: 4,
    summary: '시골에서 상경하여 수남이네 점원 생활을 하는 수남이가 자전거 때문에 양심의 가책을 느끼며 성장해가는 과정을 다룬 동화입니다.',
    thoughts: '수남이가 바람 때문에 다른 차에 흠집을 내고 도망쳤을 때 가슴이 콩닥거렸습니다. 거짓말을 하지 않고 솔직하게 용서를 구하는 용기가 얼마나 중요한지 알게 되었습니다.',
    isFeatured: false,
    teacherComment: '주인공의 심리 변화와 양심에 대해 잘 생각해보았네요.',
    createdAt: '2026-07-24T09:15:00.000Z'
  },
  {
    id: 'sample_log_4',
    grade: 5,
    classNum: 1,
    studentName: '박준혁',
    bookTitle: '코스모스 (청소년판)',
    author: '칼 세이건',
    publisher: '사이언스북스',
    genre: '과학',
    readDate: '2026-07-18',
    rating: 5,
    summary: '우주의 탄생부터 별의 수명, 외계 생명체의 가능성과 과학 기술의 역사까지 거대한 우주의 비밀을 쉽고 재미있게 소개합니다.',
    thoughts: '우리가 사는 지구는 우주 전체에서 작은 점 하나에 불과하다는 사실이 경이로웠습니다. 미래에 우주 과학자가 되어 새로운 별을 탐사하고 싶다는 꿈이 생겼습니다.',
    isFeatured: true,
    teacherComment: '우주에 대한 탐구열과 진로에 대한 다짐이 상남자처럼 멋집니다! 응원합니다.',
    createdAt: '2026-07-18T16:20:00.000Z'
  },
  {
    id: 'sample_log_5',
    grade: 5,
    classNum: 3,
    studentName: '최유진',
    bookTitle: '아몬드',
    author: '손원평',
    publisher: '창비',
    genre: '문학',
    readDate: '2026-07-15',
    rating: 5,
    summary: '편도체가 작아 감정을 느끼지 못하는 윤재가 세상과 타인과의 관계를 배우며 진정한 감정과 공감을 깨달아가는 소설입니다.',
    thoughts: '타인의 고통에 공감하는 것이 당연한 게 아니라 따뜻한 관심이 필요하다는 것을 깨달았습니다. 친구들의 마음을 이해하려고 노력하는 다정한 사람이 되고 싶습니다.',
    isFeatured: false,
    teacherComment: '공감과 이해의 가치에 대해 훌륭하게 정리해주었습니다.',
    createdAt: '2026-07-15T11:00:00.000Z'
  },
  {
    id: 'sample_log_6',
    grade: 5,
    classNum: 2,
    studentName: '김민준',
    bookTitle: '세종대왕과 집현전 학자들',
    author: '이덕일',
    publisher: '역사아이',
    genre: '역사',
    readDate: '2026-07-25',
    rating: 5,
    summary: '백성을 사랑하는 마음으로 훈민정음을 창제하신 세종대왕과 집현전 학자들의 불꽃같은 연구 과정을 실감 나게 풀어낸 인물 역사책입니다.',
    thoughts: '한글이 소리 글자로서 얼마나 위대하고 과학적인지 새삼 깨달았습니다. 세종대왕의 애민 정신을 받들어 아름다운 우리말을 지켜나가겠습니다.',
    isFeatured: false,
    teacherComment: '',
    createdAt: '2026-07-25T13:40:00.000Z'
  },
  {
    id: 'sample_log_7',
    grade: 6,
    classNum: 1,
    studentName: '정수아',
    bookTitle: '샬롯의 거미줄',
    author: '엘윈 브룩 화이트',
    publisher: '시공주니어',
    genre: '문학',
    readDate: '2026-07-21',
    rating: 5,
    summary: '꼬마 돼지 윌버와 거미 샬롯의 진실하고 아름다운 우정 이야기. 샬롯은 글자를 짜 넣어 윌버의 생명을 구합니다.',
    thoughts: '샬롯이 죽는 순간에도 친구를 위해 끝까지 최선을 다한 우정이 큰 울림을 주었습니다. 소중한 친구에게 진심을 다하는 법을 배웠습니다.',
    isFeatured: false,
    teacherComment: '친구와의 유대감을 잘 들여다본 정성스러운 독서록입니다.',
    createdAt: '2026-07-21T15:10:00.000Z'
  },
  {
    id: 'sample_log_8',
    grade: 5,
    classNum: 2,
    studentName: '이서연',
    bookTitle: '10대를 위한 경제학 교실',
    author: '한진수',
    publisher: '자음과모음',
    genre: '사회/경제',
    readDate: '2026-07-23',
    rating: 4,
    summary: '용돈 관리부터 기회비용, 물가, 무역까지 우리 일상 속에 숨어있는 기초 경제 원리를 다양한 사례로 쉽게 풀어준 책입니다.',
    thoughts: '기회비용 개념을 배운 후 합리적인 용돈 지출 습관을 가져야겠다고 생각했습니다. 사고 싶은 것보다 꼭 필요한 것을 먼저 파악하겠습니다.',
    isFeatured: false,
    teacherComment: '',
    createdAt: '2026-07-23T18:00:00.000Z'
  }
];
